name: AuthentikRoyalty
favicon: null
layout_spectrum: 0.7766145537607372
typography_spectrum: 0.33608193323016167
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.6428223380353302
  lightness: 0.17791287857107818
  saturation: 0.7539142337627709
  rhythmicContrast: 0.9786294170189649
purpose: []
