name: AuthentikRoyalty
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.6344086
  brandStrength: 0.9050179
  lightness: 0.5358423
  brandColors:
    - '#020106'
    - '#EFE6D7'
    - '#432A3F'
    - '#5A4652'
    - '#666671'
  rhythmicContrast: 0.7616488
typography_spectrum: 0.7724015
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.3566308
favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
