title: Young AUTHENTIK Brand
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.5752688
  brandStrength: 0.8602151
  lightness: 0.7329749
  brandColors:
    - '#E5DEC1'
    - '#9C983D'
    - '#11101E'
    - '#71521C'
    - '#D7DF05'
  rhythmicContrast: 0.7616488
cta:
  bucket: null
  version: null
  domain: null
favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
name: AuthentikRoyalty
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.7724015
layout_spectrum: 1
