cta:
  bucket: null
  version: null
  domain: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.5752688
  brandStrength: 0.7311828
  lightness: 0.7329749
  brandColors:
    - '#E3E8E4'
    - '#C0BDB6'
    - '#0B0A10'
    - '#3B3B3B'
    - '#646665'
  rhythmicContrast: 0.7616488
typography_spectrum: 0.7724015
layout_spectrum: 0.9444444
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: AuthentikRoyalty
